CPLYTM-343 Add terminal spinner function
complytime/complyctl pull request #13
Opened 2024-12-06 19:21 UTC by d10n

2024-12-09 14:41 UTC, hbraswelrh reviewed
LGTM

2024-12-09 16:06 UTC, jpower432 requested changes
Added a couple suggestions here. One of them is just a nit.

2024-12-09 16:06 UTC, jpower432 commented on pkg/utils.go
> +package pkg
Since `pkg` by convention is used to store other packages, I think importing from here would unexpected. If this is intended to be a top-level package like `version` is, can this please be renamed to something more descriptive?

2024-12-09 16:06 UTC, jpower432 commented on pkg/utils.go
> +var out io.Writer = os.Stdout
Nit: I see that the `out` variable is being set to something more easily testable during unit testing. I think passing this in as an argument to `ShowSpinner` instead of setting it at the package level makes the dependency more explicit and reduces the chance of it being modified somewhere else in the package.

2024-12-09 16:30 UTC, d10n commented on pkg/utils.go
> +var out io.Writer = os.Stdout
I weakly disagree but I'll make the change.
I originally considered making this an argument, but it would always be stdout except for tests, so it would be annoying, and I made a choice between annoyance with full test coverage, a helper function with less test coverage, and no annoyance with full test coverage

2024-12-09 17:47 UTC, jpower432 commented on pkg/utils.go
> +var out io.Writer = os.Stdout
Thanks @d10n. It might be worth waiting for another review so see if other folks might disagree with me as well. This is non-blocking comment from me.

2024-12-11 14:44 UTC, jpower432 approved these changes
LGTM

2024-12-11 15:10 UTC, hbraswelrh approved these changes
LGTM

2024-12-11 15:11 UTC, d10n commented
We're looking at TUI libraries and some have this built-in. Let's merge this for now and remove it upon picking one

2024-12-11 15:12 UTC, merged