CPLYTM-417: add the scan subcommand to the complytime CLI
complytime/complyctl pull request #14
Opened 2024-12-17 23:41 UTC by jpower432

## What Changed?

- Packages that exist just to support the CLI were moved to `internal`.
- A `complytime` package was added to hold core logic
- The scan subcommand was added

2024-12-18 17:57 UTC, jpower432 commented
Putting this back in draft because rebasing a branch on a dependency is going to require this to be changed.

2024-12-19 12:37 UTC, d10n submitted a review, later dismissed

2024-12-19 12:41 UTC, d10n commented on internal/complytime/configuration_test.go
Just needs a license comment

2024-12-19 12:54 UTC, d10n submitted a review, later dismissed

2024-12-23 19:15 UTC, gvauter approved these changes, later dismissed
lgtm

2024-12-23 19:26 UTC, hbraswelrh requested changes
LGTM

2024-12-23 19:26 UTC, hbraswelrh commented on cmd/complytime/option/common.go
> +// Common options for the ComplyTome CLI.
Just change typo to use ComplyTime

2024-12-23 19:26 UTC, hbraswelrh commented on cmd/complytime/option/common.go
> +// BindFlags populate Common options from a user-specified flags.
Nit pick- delete "a" for clarity

2024-12-23 19:29 UTC, hbraswelrh approved these changes
LGTM

2024-12-23 19:37 UTC, d10n approved these changes

2024-12-23 19:39 UTC, gvauter approved these changes
lgtm

2024-12-23 19:40 UTC, merged