CPLYTM-417: add generate command
complytime/complyctl pull request #15
Opened 2024-12-18 23:06 UTC by gvauter

Adds `generate` command to CLI.

2024-12-19 21:37 UTC, jpower432 requested changes
Looks good. Left a couple minor comments.

2024-12-19 21:37 UTC, jpower432 commented on cmd/complytime/cli/generate.go
> +		Short:   "Generate PVP policy from component definition",
I might suggest changing this to "from assessment plan"  since that is the optional input. This is factually true, but it might not be as apparent to the end user.

2024-12-19 21:37 UTC, jpower432 commented on cmd/complytime/cli/generate.go
> +		Example: "complytime genereate assessment-plan.json",
```suggestion
		Example: "complytime generate assessment-plan.json",
```

2024-12-19 21:37 UTC, jpower432 commented on cmd/complytime/cli/generate_test.go
> +func TestSetOptsFromArgs(t *testing.T) {
Nit: This could probably use a negative test here as well

2024-12-23 21:41 UTC, hbraswelrh reviewed
LGTM and left a minor change

2024-12-23 21:41 UTC, hbraswelrh commented on cmd/complytime/cli/generate_test.go
> +func TestSetOptsFromArgsEmtpy(t *testing.T) {
@gvauter  function for test needs to be reworded -
 `func TestSetOptsFromArgsEmpty(...)`.

2025-01-02 15:30 UTC, d10n approved these changes

2025-01-02 15:47 UTC, hbraswelrh approved these changes
LGTM

2025-01-06 15:49 UTC, jpower432 approved these changes
LGTM. One nit.

2025-01-06 15:49 UTC, jpower432 commented on internal/complytime/errors.go
> +// SPDX-License-Identifier: Apache-2.0
Nit: Was this a rebasing error or a placeholder file to capture errors in the future?

2025-01-06 19:30 UTC, merged